name = "Wave6G"
uuid = "870c4b53-bdcb-485d-984e-896e370e9ec6"
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ArgParse = "1"
Arpack = "0.5, 0.6"
CSV = "0.10"
CUDA = "5.8.5"
ChainRulesCore = "1"
DataFrames = "1"
DelimitedFiles = "1.9.1"
FFTW = "1.10.0"
FilePathsBase = "0.9, 0.10"
Flux = "0.14, 0.15, 0.16"
JLD2 = "0.4, 0.5, 0.6"
Optim = "1"
Plots = "1"
Revise = "3"
TensorOperations = "5"
Wavelets = "0.10.1"
Zygote = "0.6, 0.7"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
